# Generated by Django 3.0.3 on 2020-02-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=50, verbose_name='Имя отправителя:')),
                ('ticket_email', models.CharField(max_length=70, verbose_name='Почта отправителя:')),
                ('ticket_text', models.TextField(verbose_name='Сообщение отправителя:')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
