# Generated by Django 3.0.4 on 2020-03-11 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='username_author',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='Имя пользователя отправителя:'),
            preserve_default=False,
        ),
    ]
